// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewInfo = "review_info"

// ReviewInfo mapped from table <review_info>
type ReviewInfo struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	CreateBy       string     `gorm:"column:create_by;not null;comment:创建方标识" json:"create_by"`
	UpdateBy       string     `gorm:"column:update_by;not null;comment:更新方标识" json:"update_by"`
	CreateAt       time.Time  `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"`
	UpdateAt       time.Time  `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"`
	Version        int32      `gorm:"column:version;not null;comment:乐观锁标记" json:"version"`
	DeleteAt       *time.Time `gorm:"column:delete_at;comment:逻辑删除标记" json:"delete_at"`
	ReviewID       *int64     `gorm:"column:review_id;comment:评价id" json:"review_id"`
	Content        string     `gorm:"column:content;not null;comment:评价内容" json:"content"`
	Score          int32      `gorm:"column:score;not null;comment:评分" json:"score"`
	ServiceScore   int32      `gorm:"column:service_score;not null;comment:商家服务评分" json:"service_score"`
	ExpressScore   int32      `gorm:"column:express_score;not null;comment:物流评分" json:"express_score"`
	HasMedia       int32      `gorm:"column:has_media;not null;comment:是否有图或视频" json:"has_media"`
	OrderID        int64      `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`
	SkuID          int64      `gorm:"column:sku_id;not null;comment:sku id" json:"sku_id"`
	SpuID          int64      `gorm:"column:spu_id;not null;comment:spu id" json:"spu_id"`
	StoreID        *int64     `gorm:"column:store_id;comment:店铺id" json:"store_id"`
	UserID         *int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`
	Anonymous      int32      `gorm:"column:anonymous;not null;comment:是否匿名" json:"anonymous"`
	Tags           string     `gorm:"column:tags;not null;comment:标签json" json:"tags"`
	PicInfo        string     `gorm:"column:pic_info;not null;comment:媒体信息：图片" json:"pic_info"`
	VideoInfo      string     `gorm:"column:video_info;not null;comment:媒体信息：视频" json:"video_info"`
	Status         int32      `gorm:"column:status;not null;default:10;comment:状态：10待审核；20审核通过；30审核不通过；40隐藏" json:"status"`
	IsDefault      int32      `gorm:"column:is_default;not null;comment:是否默认评价" json:"is_default"`
	HasReply       int32      `gorm:"column:has_reply;not null;comment:是否有商家回复：0无；1有" json:"has_reply"`
	OpReason       string     `gorm:"column:op_reason;not null;comment:运营审核拒绝原因" json:"op_reason"`
	OpRemarks      string     `gorm:"column:op_remarks;not null;comment:运营备注" json:"op_remarks"`
	OpUser         string     `gorm:"column:op_user;not null;comment:运营者标识" json:"op_user"`
	GoodsSnapshoot string     `gorm:"column:goods_snapshoot;not null;comment:商品快照信息" json:"goods_snapshoot"`
	ExtJSON        string     `gorm:"column:ext_json;not null;comment:信息扩展" json:"ext_json"`
	CtrlJSON       string     `gorm:"column:ctrl_json;not null;comment:控制扩展" json:"ctrl_json"`
}

// TableName ReviewInfo's table name
func (*ReviewInfo) TableName() string {
	return TableNameReviewInfo
}
