// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewAppealInfo = "review_appeal_info"

// ReviewAppealInfo mapped from table <review_appeal_info>
type ReviewAppealInfo struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	CreateBy  string     `gorm:"column:create_by;not null;comment:创建方标识" json:"create_by"`
	UpdateBy  string     `gorm:"column:update_by;not null;comment:更新方标识" json:"update_by"`
	CreateAt  time.Time  `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"`
	UpdateAt  time.Time  `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"`
	Version   int32      `gorm:"column:version;not null;comment:乐观锁标记" json:"version"`
	DeleteAt  *time.Time `gorm:"column:delete_at;comment:逻辑删除标记" json:"delete_at"`
	AppealID  *int64     `gorm:"column:appeal_id;comment:申诉id" json:"appeal_id"`
	ReviewID  *int64     `gorm:"column:review_id;comment:评价id" json:"review_id"`
	StoreID   *int64     `gorm:"column:store_id;comment:店铺id" json:"store_id"`
	Status    int32      `gorm:"column:status;not null;default:10;comment:状态：10待审核；20申诉通过；30申诉驳回" json:"status"`
	Reason    string     `gorm:"column:reason;not null;comment:申诉原因类别" json:"reason"`
	Content   string     `gorm:"column:content;not null;comment:申诉内容描述" json:"content"`
	PicInfo   string     `gorm:"column:pic_info;not null;comment:媒体信息：图片" json:"pic_info"`
	VideoInfo string     `gorm:"column:video_info;not null;comment:媒体信息：视频" json:"video_info"`
	OpRemarks string     `gorm:"column:op_remarks;not null;comment:运营备注" json:"op_remarks"`
	OpUser    string     `gorm:"column:op_user;not null;comment:运营者标识" json:"op_user"`
	ExtJSON   string     `gorm:"column:ext_json;not null;comment:信息扩展" json:"ext_json"`
	CtrlJSON  string     `gorm:"column:ctrl_json;not null;comment:控制扩展" json:"ctrl_json"`
}

// TableName ReviewAppealInfo's table name
func (*ReviewAppealInfo) TableName() string {
	return TableNameReviewAppealInfo
}
